import { api, getAccessToken } from "./apiClient";
import type {
  Guard, ClientSite, ArmouryItem, ArmouryLog, K9Dog, K9Log, K9HealthInspection,
  Vehicle, VehicleTripLog, FuelRequisitionLog, MaintenanceServiceLog, DriverRecord,
  DailyVehicleInspection, FleetBreakdownEmergency, Incident,
  DutyRoster, PatrolInspectionLog, AdminRequisition,
  TrainingCohort, RecruitTrainee, ITServer, ITSupportTicket, ITAsset,
  Invoice, Expense, CashierTransaction, Lead, Campaign, Reminder,
  Complaint, DisciplinaryAction, SiteDeployment, DeploymentOrder,
  RegionalOffice, Region, LeaveRequest, WorkflowDefinition, Approval,   TransportRequest,
  SiteSurvey,
  ContractInquiry,
  DocumentRecord, JobPosting, Candidate, PerformanceReviewRecord, ContractRecord,
  NotificationRecord,
} from "../types";

export const domainApi = {
  guards: {
    list: () => api.get<Guard[]>("/guards"),
    create: (data: Omit<Guard, "id">) => api.post<Guard>("/guards", data),
    update: (id: string, data: Partial<Guard>) => api.put<Guard>(`/guards/${id}`, data),
    remove: (id: string) => api.delete(`/guards/${id}`),
    lifecycle: (id: string, data: Partial<Guard>) => api.put<Guard>(`/guards/${id}/lifecycle`, data),
    issueId: (id: string, data: { idCardNumber: string; idCardExpiryDate: string }) => api.put<Guard>(`/guards/${id}/issue-id`, data),
  },
  sites: {
    list: () => api.get<ClientSite[]>("/sites"),
    create: (data: Omit<ClientSite, "id">) => api.post<ClientSite>("/sites", data),
    update: (id: string, data: Partial<ClientSite>) => api.put<ClientSite>(`/sites/${id}`, data),
    remove: (id: string) => api.delete(`/sites/${id}`),
  },
  incidents: {
    list: () => api.get<Incident[]>("/incidents"),
    create: (data: Omit<Incident, "id">) => api.post<Incident>("/incidents", data),
    investigate: (id: string) => api.put(`/incidents/${id}/investigate`, {}),
    escalate: (id: string) => api.put(`/incidents/${id}/escalate`, {}),
    opsClose: (id: string) => api.put(`/incidents/${id}/ops-close`, {}),
    resolve: (id: string) => api.put(`/incidents/${id}/resolve`, {}),
  },
  vehicles: {
    list: () => api.get<Vehicle[]>("/vehicles"),
    create: (data: Omit<Vehicle, "id">) => api.post<Vehicle>("/vehicles", data),
  },
  invoices: {
    list: () => api.get<Invoice[]>("/invoices"),
    create: (data: Omit<Invoice, "id">) => api.post<Invoice>("/invoices", data),
    approve: (id: string) => api.put<Invoice>(`/invoices/${id}/approve`, {}),
    update: (id: string, data: Partial<Invoice>) => api.put<Invoice>(`/invoices/${id}`, data),
    remove: (id: string) => api.delete(`/invoices/${id}`),
    remind: (id: string, recipient?: string) => api.post<Reminder>(`/invoices/${id}/remind`, recipient ? { recipient } : {}),
  },
  collections: {
    list: () => api.get<Invoice[]>("/collections"),
  },
  expenses: {
    list: () => api.get<Expense[]>("/expenses"),
    create: (data: Omit<Expense, "id">) => api.post<Expense>("/expenses", data),
    approve: (id: string) => api.put(`/expenses/${id}/approve`, {}),
    gmApprove: (id: string) => api.put(`/expenses/${id}/gm-approve`, {}),
    reject: (id: string) => api.put(`/expenses/${id}/reject`, {}),
  },
  contracts: {
    list: () => api.get<ContractRecord[]>("/contracts"),
    create: (data: Omit<ContractRecord, "id">) => api.post<ContractRecord>("/contracts", data),
    update: (id: string, data: Partial<ContractRecord>) => api.put<ContractRecord>(`/contracts/${id}`, data),
    issue: (id: string) => api.put<ContractRecord>(`/contracts/${id}`, { action: "issue" }),
    approve: (id: string) => api.put<ContractRecord>(`/contracts/${id}`, { action: "approve" }),
    archive: (id: string) => api.put<ContractRecord>(`/contracts/${id}`, { action: "archive" }),
    voidContract: (id: string, voidReason: string) => api.put<ContractRecord>(`/contracts/${id}`, { action: "void", voidReason }),
  },
  cashierTxns: {
    list: () => api.get<CashierTransaction[]>("/cashier-transactions"),
    create: (data: Omit<CashierTransaction, "id">) => api.post<CashierTransaction>("/cashier-transactions", data),
    approve: (id: string) => api.put<CashierTransaction>(`/cashier-transactions/${id}/approve`, {}),
    reject: (id: string) => api.put<CashierTransaction>(`/cashier-transactions/${id}/reject`, {}),
  },
  leads: {
    list: () => api.get<Lead[]>("/leads"),
    create: (data: Omit<Lead, "id">) => api.post<Lead>("/leads", data),
    update: (id: string, data: Partial<Lead>) => api.put<Lead>(`/leads/${id}`, data),
    remove: (id: string) => api.delete(`/leads/${id}`),
  },
  k9s: {
    list: () => api.get<K9Dog[]>("/k9s"),
    create: (data: Omit<K9Dog, "id" | "code">) => api.post<K9Dog>("/k9s", data),
    update: (id: string, data: Partial<K9Dog>) => api.put<K9Dog>(`/k9s/${id}`, data),
    remove: (id: string) => api.delete(`/k9s/${id}`),
  },
  k9Logs: {
    list: () => api.get<K9Log[]>("/k9-logs"),
    create: (data: Omit<K9Log, "id">) => api.post<K9Log>("/k9-logs", data),
  },
  k9HealthInspections: {
    list: () => api.get<K9HealthInspection[]>("/k9-health"),
    create: (data: Omit<K9HealthInspection, "id" | "inspectionCode">) => api.post<K9HealthInspection>("/k9-health", data),
    update: (id: string, data: Partial<K9HealthInspection>) => api.put<K9HealthInspection>(`/k9-health/${id}`, data),
    remove: (id: string) => api.delete(`/k9-health/${id}`),
  },
  armoury: {
    list: () => api.get<ArmouryItem[]>("/armoury"),
    create: (data: Omit<ArmouryItem, "id">) => api.post<ArmouryItem>("/armoury", data),
    update: (id: string, data: Partial<ArmouryItem>) => api.put<ArmouryItem>(`/armoury/${id}`, data),
    remove: (id: string) => api.delete(`/armoury/${id}`),
  },
  armouryLogs: {
    list: () => api.get<ArmouryLog[]>("/armoury-logs"),
    issue: (data: any) => api.post<ArmouryLog>("/armoury-logs", data),
    return: (id: string, data: any) => api.put<ArmouryLog>(`/armoury-logs/${id}/return`, data),
  },
  trips: {
    list: () => api.get<VehicleTripLog[]>("/trips"),
    create: (data: Omit<VehicleTripLog, "id" | "tripCode">) => api.post<VehicleTripLog>("/trips", data),
    update: (id: string, data: Partial<VehicleTripLog>) => api.put<VehicleTripLog>(`/trips/${id}`, data),
    remove: (id: string) => api.delete(`/trips/${id}`),
  },
  fuelLogs: {
    list: () => api.get<FuelRequisitionLog[]>("/fuel-logs"),
    create: (data: Omit<FuelRequisitionLog, "id" | "voucherCode">) => api.post<FuelRequisitionLog>("/fuel-logs", data),
    approve: (id: string) => api.put<FuelRequisitionLog>(`/fuel-logs/${id}/approve`, {}),
    update: (id: string, data: Partial<FuelRequisitionLog>) => api.put<FuelRequisitionLog>(`/fuel-logs/${id}`, data),
  },
  maintenanceLogs: {
    list: () => api.get<MaintenanceServiceLog[]>("/maintenance"),
    create: (data: Omit<MaintenanceServiceLog, "id" | "serviceCode">) => api.post<MaintenanceServiceLog>("/maintenance", data),
    approve: (id: string) => api.put<MaintenanceServiceLog>(`/maintenance/${id}/approve`, {}),
    update: (id: string, data: Partial<MaintenanceServiceLog>) => api.put<MaintenanceServiceLog>(`/maintenance/${id}`, data),
  },
  drivers: {
    list: () => api.get<DriverRecord[]>("/drivers"),
    create: (data: Omit<DriverRecord, "id" | "driverCode">) => api.post<DriverRecord>("/drivers", data),
    update: (id: string, data: Partial<DriverRecord>) => api.put<DriverRecord>(`/drivers/${id}`, data),
    approve: (id: string) => api.put<DriverRecord>(`/drivers/${id}/approve`, {}),
  },
  inspections: {
    list: () => api.get<DailyVehicleInspection[]>("/inspections"),
    create: (data: Omit<DailyVehicleInspection, "id" | "inspectionCode">) => api.post<DailyVehicleInspection>("/inspections", data),
    update: (id: string, data: Partial<DailyVehicleInspection>) => api.put<DailyVehicleInspection>(`/inspections/${id}`, data),
  },
  breakdowns: {
    list: () => api.get<FleetBreakdownEmergency[]>("/breakdowns"),
    create: (data: Omit<FleetBreakdownEmergency, "id" | "incidentCode">) => api.post<FleetBreakdownEmergency>("/breakdowns", data),
    update: (id: string, data: Partial<FleetBreakdownEmergency>) => api.put<FleetBreakdownEmergency>(`/breakdowns/${id}`, data),
  },
  dutyRoster: {
    list: () => api.get<DutyRoster[]>("/roster"),
    create: (data: Omit<DutyRoster, "id">) => api.post<DutyRoster>("/roster", data),
    update: (id: string, data: Partial<DutyRoster>) => api.put<DutyRoster>(`/roster/${id}`, data),
    remove: (id: string) => api.delete(`/roster/${id}`),
  },
  patrolInspections: {
    list: () => api.get<PatrolInspectionLog[]>("/patrol-inspections"),
    create: (data: Omit<PatrolInspectionLog, "id" | "inspectionCode">) => api.post<PatrolInspectionLog>("/patrol-inspections", data),
    update: (id: string, data: Partial<PatrolInspectionLog>) => api.put<PatrolInspectionLog>(`/patrol-inspections/${id}`, data),
    remove: (id: string) => api.delete(`/patrol-inspections/${id}`),
  },
  requisitions: {
    list: () => api.get<AdminRequisition[]>("/requisitions"),
    create: (data: Omit<AdminRequisition, "id">) => api.post<AdminRequisition>("/requisitions", data),
    update: (id: string, data: Partial<AdminRequisition>) => api.put<AdminRequisition>(`/requisitions/${id}`, data),
    remove: (id: string) => api.delete(`/requisitions/${id}`),
  },
  trainingCohorts: {
    list: () => api.get<TrainingCohort[]>("/cohorts"),
    create: (data: Omit<TrainingCohort, "id" | "code">) => api.post<TrainingCohort>("/cohorts", data),
    update: (id: string, data: Partial<TrainingCohort>) => api.put<TrainingCohort>(`/cohorts/${id}`, data),
    remove: (id: string) => api.delete(`/cohorts/${id}`),
  },
  recruitTrainees: {
    list: () => api.get<RecruitTrainee[]>("/trainees"),
    create: (data: Omit<RecruitTrainee, "id" | "traineeCode">) => api.post<RecruitTrainee>("/trainees", data),
    update: (id: string, data: Partial<RecruitTrainee>) => api.put<RecruitTrainee>(`/trainees/${id}`, data),
    remove: (id: string) => api.delete(`/trainees/${id}`),
    graduate: (id: string, forceNumber: string) => api.put<RecruitTrainee>(`/trainees/${id}/graduate`, { forceNumber }),
  },
  itServers: {
    list: () => api.get<ITServer[]>("/it-servers"),
    create: (data: Omit<ITServer, "id">) => api.post<ITServer>("/it-servers", data),
    update: (id: string, data: Partial<ITServer>) => api.put<ITServer>(`/it-servers/${id}`, data),
    remove: (id: string) => api.delete(`/it-servers/${id}`),
  },
  itTickets: {
    list: () => api.get<ITSupportTicket[]>("/it-tickets"),
    create: (data: Omit<ITSupportTicket, "id" | "ticketCode">) => api.post<ITSupportTicket>("/it-tickets", data),
    update: (id: string, data: Partial<ITSupportTicket>) => api.put<ITSupportTicket>(`/it-tickets/${id}`, data),
    remove: (id: string) => api.delete(`/it-tickets/${id}`),
  },
  itAssets: {
    list: () => api.get<ITAsset[]>("/it-assets"),
    create: (data: Omit<ITAsset, "id" | "assetCode">) => api.post<ITAsset>("/it-assets", data),
    update: (id: string, data: Partial<ITAsset>) => api.put<ITAsset>(`/it-assets/${id}`, data),
    remove: (id: string) => api.delete(`/it-assets/${id}`),
  },
  regions: {
    list: () => api.get<Region[]>("/regions"),
    create: (data: Omit<RegionalOffice, "id">) => api.post<RegionalOffice>("/regions", data),
    update: (id: string, data: Partial<RegionalOffice>) => api.put<RegionalOffice>(`/regions/${id}`, data),
    remove: (id: string) => api.delete(`/regions/${id}`),
  },
  regionalOffices: {
    list: () => api.get<RegionalOffice[]>("/regional-offices"),
  },
  leaveRequests: {
    list: () => api.get<LeaveRequest[]>("/leave-requests"),
    create: (data: Omit<LeaveRequest, "id">) => api.post<LeaveRequest>("/leave-requests", data),
    act: (id: string, action: "Approved" | "Rejected", comment?: string) => api.put(`/approvals/${id}/act`, { action, comment }),
  },
  campaigns: {
    list: () => api.get<Campaign[]>("/campaigns"),
    create: (data: Omit<Campaign, "id">) => api.post<Campaign>("/campaigns", data),
    update: (id: string, data: Partial<Campaign>) => api.put<Campaign>(`/campaigns/${id}`, data),
    approveBudget: (id: string) => api.put(`/campaigns/${id}/approve-budget`, {}),
    gmApprove: (id: string) => api.put(`/campaigns/${id}/gm-approve`, {}),
  },
  complaints: {
    list: () => api.get<Complaint[]>("/complaints"),
    create: (data: Omit<Complaint, "id">) => api.post<Complaint>("/complaints", data),
    update: (id: string, data: Partial<Complaint>) => api.put<Complaint>(`/complaints/${id}`, data),
    resolve: (id: string, data: { resolutionNotes?: string; satisfactionRating?: number }) => api.put<Complaint>(`/complaints/${id}/resolve`, data),
    refer: (id: string, notes?: string) => api.put<Complaint>(`/complaints/${id}/refer`, { notes }),
  },
  disciplinary: {
    list: () => api.get<DisciplinaryAction[]>("/disciplinary"),
    create: (data: Omit<DisciplinaryAction, "id" | "createdAt">) => api.post<DisciplinaryAction>("/disciplinary", data),
    regionalApprove: (id: string) => api.put(`/disciplinary/${id}/regional-approve`, {}),
    opsApprove: (id: string) => api.put(`/disciplinary/${id}/ops-approve`, {}),
    hrApprove: (id: string) => api.put(`/disciplinary/${id}/hr-approve`, {}),
    reject: (id: string, notes?: string) => api.put(`/disciplinary/${id}/reject`, { notes }),
  },
  deployments: {
    list: () => api.get<SiteDeployment[]>("/deployments"),
    create: (data: Omit<SiteDeployment, "id" | "deployedAt">) => api.post<SiteDeployment>("/deployments", data),
    end: (id: string) => api.put(`/deployments/${id}/end`, {}),
  },
  deploymentOrders: {
    list: () => api.get<DeploymentOrder[]>("/deployment-orders"),
    create: (data: Omit<DeploymentOrder, "id" | "orderCode" | "status" | "assignedGuardIds">) => api.post<DeploymentOrder>("/deployment-orders", data),
    assign: (id: string, guardIds: string[]) => api.put<DeploymentOrder>(`/deployment-orders/${id}/assign`, { guardIds }),
    cancel: (id: string) => api.put<DeploymentOrder>(`/deployment-orders/${id}/cancel`, {}),
  },
  workflows: {
    list: () => api.get<WorkflowDefinition[]>("/workflows"),
    create: (data: Omit<WorkflowDefinition, "id">) => api.post<WorkflowDefinition>("/workflows", data),
    update: (id: string, data: Partial<WorkflowDefinition>) => api.put<WorkflowDefinition>(`/workflows/${id}`, data),
    remove: (id: string) => api.delete(`/workflows/${id}`),
  },
  approvals: {
    list: () => api.get<Approval[]>("/approvals"),
    create: (data: Omit<Approval, "id">) => api.post<Approval>("/approvals", data),
    act: (id: string, action: "Approved" | "Rejected", comment?: string) => api.put(`/approvals/${id}/act`, { action, comment }),
  },
  transportRequests: {
    list: () => api.get<TransportRequest[]>("/transport-requests"),
    create: (data: Omit<TransportRequest, "id" | "requestCode" | "status">) => api.post<TransportRequest>("/transport-requests", data),
    act: (id: string, data: { action: "Approved" | "Declined"; assignedVehicleId?: string; assignedVehicle?: string; assignedDriverId?: string; assignedDriver?: string; assignedRiderId?: string; assignedRider?: string; declinedReason?: string }) => api.put<TransportRequest>(`/transport-requests/${id}/act`, data),
  },
  siteSurveys: {
    list: () => api.get<SiteSurvey[]>("/site-surveys"),
    create: (data: Omit<SiteSurvey, "id" | "surveyCode" | "status">) => api.post<SiteSurvey>("/site-surveys", data),
    start: (id: string) => api.put<SiteSurvey>(`/site-surveys/${id}/start`, {}),
    complete: (id: string, data: Partial<SiteSurvey>) => api.put<SiteSurvey>(`/site-surveys/${id}/complete`, data),
    cancel: (id: string) => api.put<SiteSurvey>(`/site-surveys/${id}/cancel`, {}),
  },
  contractInquiries: {
    list: () => api.get<ContractInquiry[]>("/contract-inquiries"),
    create: (data: Omit<ContractInquiry, "id" | "inquiryCode" | "status">) => api.post<ContractInquiry>("/contract-inquiries", data),
    respond: (id: string, data: { responseType: "Confirmation" | "Full Copy"; responseNotes?: string; responsePath?: string }) => api.put<ContractInquiry>(`/contract-inquiries/${id}/respond`, data),
  },
  documents: {
    list: () => api.get<DocumentRecord[]>("/documents"),
    upload: (formData: FormData) => {
      const token = getAccessToken();
      return fetch("/api/documents/upload", {
        method: "POST",
        headers: token ? { Authorization: `Bearer ${token}` } : {},
        body: formData,
      }).then(r => r.json());
    },
    remove: (id: string) => api.delete(`/documents/${id}`),
  },
  jobPostings: {
    list: () => api.get<JobPosting[]>("/job-postings"),
    create: (data: Omit<JobPosting, "id">) => api.post<JobPosting>("/job-postings", data),
    update: (id: string, data: Partial<JobPosting>) => api.put<JobPosting>(`/job-postings/${id}`, data),
  },
  candidates: {
    list: () => api.get<Candidate[]>("/candidates"),
    create: (data: Omit<Candidate, "id">) => api.post<Candidate>("/candidates", data),
    update: (id: string, data: Partial<Candidate>) => api.put<Candidate>(`/candidates/${id}`, data),
  },
  performanceReviews: {
    list: () => api.get<PerformanceReviewRecord[]>("/performance-reviews"),
    create: (data: Omit<PerformanceReviewRecord, "id">) => api.post<PerformanceReviewRecord>("/performance-reviews", data),
  },
  customRoles: {
    list: () => api.get<any[]>("/custom-roles"),
    create: (data: any) => api.post<any>("/custom-roles", data),
    remove: (id: string) => api.delete(`/custom-roles/${id}`),
  },
  analytics: {
    summary: () => api.get<any>("/analytics/summary"),
  },
  notifications: {
    list: () => api.get<NotificationRecord[]>("/notifications"),
    create: (data: { type: string; title: string; message: string; module?: string; targetRole?: string }) =>
      api.post<NotificationRecord>("/notifications", data),
    markRead: (id: string) => api.put<NotificationRecord>(`/notifications/${id}/read`, {}),
    markAllRead: () => api.put<{ ok: boolean }>("/notifications/read-all", {}),
    remove: (id: string) => api.delete<{ ok: boolean }>(`/notifications/${id}`),
  },
  seed: () => api.post<any>("/auth/seed"),
};
