/**
 * Single source of truth for RBAC.
 * Generated module: server + client both import from here.
 * Do not duplicate MODULE_PERMISSIONS elsewhere.
 */

export type AccessLevel = "view" | "full";

export const MODULE_PERMISSIONS: Record<string, Partial<Record<string, AccessLevel>>> = {
  operations: {
    "Operations Manager": "view",
    "Regional Manager": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
    "Guard Officer": "view",
  },
  guards: {
    "HR Manager": "full",
    "HR Assistant": "full",
    "Records Officer": "full",
    "Operations Manager": "view",
    "Regional Manager": "view",
    "Armorer": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
    "Training Officer": "view",
  },
  sites: {
    "Business Development Manager": "full",
    "Sales and Marketing Supervisor": "full",
    "Operations Manager": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
    "Guard Officer": "view",
  },
  armoury: {
    "Armorer": "full",
    "Operations Manager": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  incidents: {
    "Investigations Officer": "full",
    "Operations Manager": "full",
    "Regional Manager": "full",
    "Guard Officer": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  vehicles: {
    "Fleet Manager": "full",
    "Operations Manager": "view",
    "Regional Manager": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  invoices: {
    "Finance Manager": "full",
    "Accountant": "full",
    "Assistant Accountant": "view",
    "Cashier": "view",
    "Internal Auditor": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  expenses: {
    "Finance Manager": "full",
    "Accountant": "full",
    "Assistant Accountant": "view",
    "Cashier": "view",
    "Internal Auditor": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  leads: {
    "Business Development Manager": "full",
    "Sales and Marketing Supervisor": "full",
    "Operations Manager": "view",
    "Regional Manager": "view",
  },
  k9s: {
    "K9 Supervisor": "full",
    "K9 Handler": "view",
    "Operations Manager": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  hr: {
    "HR Manager": "full",
    "HR Assistant": "full",
    "Records Officer": "full",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  identity: {
    "Records Officer": "full",
    "HR Manager": "view",
    "HR Assistant": "view",
  },
  marketing: {
    "Business Development Manager": "full",
    "Sales and Marketing Supervisor": "full",
    "Finance Manager": "view",
    "Operations Manager": "view",
  },
  administration: {
    "Administrative Officer": "full",
  },
  it: {
    "IT Officer": "full",
  },
  finance: {
    "Finance Manager": "full",
    "Accountant": "full",
    "Assistant Accountant": "view",
    "Cashier": "full",
    "Internal Auditor": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  fleet: {
    "Fleet Manager": "full",
    "Operations Manager": "view",
    "Regional Manager": "view",
  },
  roster: {
    "Regional Manager": "full",
    "Operations Manager": "full",
  },
  patrol: {
    "Operations Manager": "full",
    "Regional Manager": "full",
    "Guard Officer": "full",
  },
  requisitions: {
    "Administrative Officer": "full",
    "HR Manager": "full",
    "Finance Manager": "view",
    "Operations Manager": "view",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  training: {
    "Training Officer": "full",
    "HR Manager": "full",
    "HR Assistant": "full",
    "Operations Manager": "view",
    "Records Officer": "view",
  },
  recruitment: {
    "HR Manager": "full",
    "HR Assistant": "full",
    "Records Officer": "view",
    "Operations Manager": "view",
    "Regional Manager": "view",
  },
  performance: {
    "HR Manager": "full",
    "Operations Manager": "full",
    "Regional Manager": "full",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  workflow: {
    "IT Officer": "full",
    "General Manager": "view",
    "Director": "view",
  },
  documents: {
    "IT Officer": "full",
    "HR Manager": "full",
    "HR Assistant": "full",
    "Records Officer": "full",
    "Finance Manager": "view",
    "Operations Manager": "view",
    "Regional Manager": "view",
    "General Manager": "view",
    "Director": "view",
  },
  campaigns: {
    "Business Development Manager": "full",
    "Sales and Marketing Supervisor": "full",
    "Finance Manager": "view",
    "Operations Manager": "view",
  },
  complaints: {
    "Business Development Manager": "full",
    "Sales and Marketing Supervisor": "full",
    "Operations Manager": "full",
    "Regional Manager": "full",
    "Investigations Officer": "full",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  disciplinary: {
    "HR Manager": "full",
    "HR Assistant": "full",
    "Operations Manager": "full",
    "Regional Manager": "full",
    "Investigations Officer": "full",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
  },
  deployments: {
    "Operations Manager": "full",
    "Regional Manager": "full",
    "Business Development Manager": "view",
  },
  directorate: {
    "General Manager": "full",
    "Director": "view",
  },
  leave: {
    "Guard Officer": "view",
    "Regional Manager": "view",
    "Operations Manager": "view",
    "HR Manager": "full",
    "HR Assistant": "full",
    "General Manager": "view",
    "Director": "view",
    "IT Officer": "view",
    "Internal Auditor": "view",
  },
  esign: {
    "Business Development Manager": "full",
    "Sales and Marketing Supervisor": "full",
    "HR Manager": "view",
    "Finance Manager": "view",
    "General Manager": "full",
    "Director": "view",
    "IT Officer": "view",
    "Administrative Officer": "view",
    "Records Officer": "full",
  },
};

export const SERVER_MODULE_TO_CLIENT: Record<string, string> = {
  guards: "hr",
  armoury: "operations",
  incidents: "operations",
  vehicles: "fleet",
  k9s: "operations",
  roster: "operations",
  patrol: "operations",
  training: "operations",
  deployments: "operations",
  complaints: "operations",
  disciplinary: "hr",
  leave: "hr",
  sites: "clients",
  leads: "marketing",
  invoices: "finance",
  expenses: "finance",
  finance: "finance",
  hr: "hr",
  recruitment: "recruitment",
  performance: "performance_reviews",
  identity: "identity",
  marketing: "marketing",
  campaigns: "marketing",
  administration: "administration",
  requisitions: "administration",
  it: "it",
  workflow: "workflow",
  documents: "documents",
  fleet: "fleet",
  directorate: "dashboard",
};

export const MODULE_DISPLAY_NAMES: Record<string, string> = {
  guards: "Guard Records",
  operations: "Operations",
  sites: "Client Sites",
  armoury: "Armoury",
  incidents: "Incidents",
  vehicles: "Fleet",
  invoices: "Invoices",
  expenses: "Expenses",
  leads: "Sales Leads",
  k9s: "K9 Management",
  hr: "Human Resources",
  identity: "Identity Cards",
  marketing: "Marketing",
  campaigns: "Campaigns",
  administration: "Administration",
  it: "IT Systems",
  finance: "Finance",
  fleet: "Fleet",
  roster: "Duty Rosters",
  patrol: "Patrol Inspections",
  requisitions: "Requisitions",
  recruitment: "Recruitment",
  training: "Training",
  performance: "Performance Reviews",
  workflow: "Workflow",
  documents: "Documents",
  complaints: "Complaints",
  disciplinary: "Disciplinary Actions",
  deployments: "Deployments",
  directorate: "Directorate",
  leave: "Leave Requests",
};
